const books = [
  {
    id: 1,
    title: "Belajar JavaScript Dasar",
    author: "Andi Prasetyo",
    year: 2021,
    description: "Panduan lengkap untuk pemula yang ingin belajar JavaScript dari nol.",
    image: "https://placehold.co/300x400?text=JavaScript+Dasar",
  },
  {
    id: 2,
    title: "React untuk Pemula",
    author: "Dina Sari",
    year: 2022,
    description: "Mengenal konsep dan praktik membuat aplikasi React modern.",
    image: "https://placehold.co/300x400?text=React+Pemula",
  },
  {
    id: 3,
    title: "HTML dan CSS Modern",
    author: "Budi Santoso",
    year: 2023,
    description: "Belajar membuat halaman website dengan HTML dan CSS.",
    image: "https://placehold.co/300x400?text=HTML+CSS",
  },
  {
    id: 4,
    title: "Dasar-Dasar Node.js",
    author: "Rina Amelia",
    year: 2022,
    description: "Panduan membangun aplikasi backend menggunakan Node.js.",
    image: "https://placehold.co/300x400?text=Node.js",
  },
  {
    id: 5,
    title: "Menguasai Bootstrap",
    author: "Fajar Nugraha",
    year: 2024,
    description: "Membuat website responsif dengan komponen Bootstrap.",
    image: "https://placehold.co/300x400?text=Bootstrap",
  },
  {
    id: 6,
    title: "Pemrograman Python",
    author: "Siti Rahma",
    year: 2021,
    description: "Pengenalan Python beserta contoh program untuk pemula.",
    image: "https://placehold.co/300x400?text=Python",
  },
  {
    id: 7,
    title: "Database MongoDB",
    author: "Dimas Saputra",
    year: 2023,
    description: "Memahami penyimpanan dan pengelolaan data dengan MongoDB.",
    image: "https://placehold.co/300x400?text=MongoDB",
  },
  {
    id: 8,
    title: "Git dan GitHub Praktis",
    author: "Nadia Putri",
    year: 2024,
    description: "Belajar version control dan kolaborasi project dengan GitHub.",
    image: "https://placehold.co/300x400?text=Git+GitHub",
  },
  {
    id: 9,
    title: "UI/UX Design untuk Pemula",
    author: "Arif Wijaya",
    year: 2025,
    description: "Mengenal dasar desain antarmuka dan pengalaman pengguna.",
    image: "https://placehold.co/300x400?text=UI+UX+Design",
  },
];

export default books;